/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.RestTemplate;

import org.springframework.http.client.observation.ClientRequestObservationContext;

import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationRegistry;
import io.micrometer.observation.ObservationHandler;


import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.concurrent.atomic.AtomicInteger;

import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationHandler;
import org.springframework.http.client.observation.ClientRequestObservationContext;




@RestController
@SpringBootApplication
public class MyApplication {
	
	private RestTemplate restTemplate;
	
    private ObservationRegistry observationRegistry;
	
    public MyApplication(ObservationRegistry registry, MeterRegistry meterRegistry) {
		this.observationRegistry = registry;
		
        this.restTemplate = new RestTemplate();
		
        this.restTemplate.setObservationRegistry(observationRegistry);
        
        AtomicInteger httpClientInFlightCounter = new AtomicInteger(0);

        Gauge.builder("http.client.requests.in_flight",  httpClientInFlightCounter, AtomicInteger::get)
             .description("Number of in-flight HTTP client requests")
             .register(meterRegistry);
        
 
        ObservationHandler<ClientRequestObservationContext> clientInFlightHandler = (new ObservationHandler<>() {

            @Override
            public void onStart(ClientRequestObservationContext context) {
                httpClientInFlightCounter.incrementAndGet();

                System.out.println("clientInFlightHandler:: onStart");
            }

            @Override
            public void onStop(ClientRequestObservationContext context) {
                System.out.println("clientInFlightHandler:: onStop");
                httpClientInFlightCounter.decrementAndGet();
            }

            @Override
            public boolean supportsContext(Observation.Context context) {
                return context instanceof ClientRequestObservationContext;
                // return true;
            }
        });


        registry.observationConfig().observationHandler(clientInFlightHandler);

	}


	@RequestMapping("/")
	String home() {
		return "Hello World!";
	}
	

	@RequestMapping("/delay")
	String delay(@RequestParam("seconds") String seconds) {
        String serverHost = System.getenv("SERVER_HOST") != null ? System.getenv("SERVER_HOST") : "server";
		String response = restTemplate.getForObject(String.format("http://%s/delay?seconds=%s", serverHost, seconds), String.class);
		System.out.println(response);

		return response;
	}
	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}

}
