/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@SpringBootApplication
public class MyApplication {

	@RequestMapping("/")
	String home() {
		return "Hello World!";
	}

	private void sleep(int milliseconds) {
		try {
			Thread.sleep(milliseconds);
		} catch(InterruptedException e) {}
	}

	@RequestMapping("/delay")
	String delay(@RequestParam("ms") int ms)  {
		sleep(ms);
		return "delayed";
	}
	
	@RequestMapping("/foo")
	String foo(@RequestParam("ms") int ms)  {
		sleep(ms);
		return "delayed";
	}

	@RequestMapping("/bar")
	String bar(@RequestParam("ms") int ms)  {
		sleep(ms);
		return "delayed";
	}

	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
}